# Declare the workspace
module(
    name = "adasisv2",
    version = "0.1",
    bazel_compatibility = [
        ">=7.6.0",
    ],
)

# Initialize the Bazel language engine
bazel_dep(name = "bazel_skylib", version = "1.9.2")

# Register access to pre-existing online BzlMod repositories
## Base macros for different programming and scripting languages
bazel_dep(name = "rules_rust", version = "0.74.0")  # Rust support
bazel_dep(name = "rules_cc", version = "0.2.22")  # C/C++ support
bazel_dep(name = "rules_python", version = "2.0.2")  # Python support

bazel_dep(name = "toolchains_llvm", version = "1.8.0", dev_dependency = True)  # LLVM Clang C++ Toolchain

# Rust
## Enable the Rust toolchain use in projects
rust = use_extension("@rules_rust//:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    versions = ["1.85.0"],
)

## Auto-generate Bazel dependency macros for modeled Rust dependencies
crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
use_repo(crate, "crates")

crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//rust:Cargo.lock",
    manifests = ["//rust:Cargo.toml"],
)

# C/C++
## Enable the C/C++ toolchain and LLVM tools for use in projects
llvm_clang = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm_clang.toolchain(
    llvm_version = "19.1.0",
)
use_repo(llvm_clang, "llvm_toolchain")

register_toolchains("@llvm_toolchain//:all")

# Python
## Enable the Python toolchain in projects
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
   is_default = True,
    python_version = "3.12",
)
